import Link from "next/link";
import { requireUser, getAuthorizedBranchIds } from "@/lib/auth/authorization";
import { sql } from "@/lib/db";

const fmt=new Intl.DateTimeFormat("es-MX",{timeZone:"America/Monterrey",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"});
const dateFmt=new Intl.DateTimeFormat("es-MX",{timeZone:"America/Monterrey",weekday:"long",day:"numeric",month:"long",year:"numeric"});
const detail=(id:string,type:string)=>type==='RECEPTION'?`/entradas/${id}`:type.startsWith('RETURN_')?`/devoluciones/${id}`:type==='EXIT'?`/salidas/${id}`:type==='TRANSFER'?`/traspasos/${id}`:'#';
const typeLabel=(v:string)=>({RECEPTION:'Recepción de mercancía',RETURN_ML:'Devolución Mercado Libre',RETURN_TIKTOK:'Devolución TikTok',RETURN_CUSTOMER:'Devolución de cliente',EXIT:'Salida de inventario',TRANSFER:'Traspaso entre sucursales'}[v]??v);
const typeShort=(v:string)=>({RECEPTION:'ENTRADA',RETURN_ML:'ENTRADA',RETURN_TIKTOK:'ENTRADA',RETURN_CUSTOMER:'ENTRADA',EXIT:'SALIDA',TRANSFER:'TRASPASO'}[v]??v);
const typeIcon=(v:string)=>v==='EXIT'?'⇥':v==='TRANSFER'?'⇄':v.startsWith('RETURN_')?'↩':'□';
const statusLabel=(v:string)=>({DRAFT:'Borrador',CLOSED:'Pendiente sistema',PENDING_POS:'Pendiente POS',POS_REGISTERED:'Registrado',POS_CORRECTION_PENDING:'Corrección POS',POS_RECONCILED:'Registrado',WAITING_RECEIPT:'Esperando recepción',RECEIVED_WITH_DIFFERENCES:'Diferencia pendiente',COMPLETED:'Completado',CANCELLED:'Cancelado'}[v]??v.replaceAll('_',' '));
const statusTone=(v:string)=>['POS_REGISTERED','POS_RECONCILED','COMPLETED'].includes(v)?'ok':['DRAFT','WAITING_RECEIPT','RECEIVED_WITH_DIFFERENCES','PENDING_POS','CLOSED','POS_CORRECTION_PENDING'].includes(v)?'warn':'muted';

export default async function Dashboard(){
  const user=await requireUser(),branches=await getAuthorizedBranchIds(user);
  const rows=branches===null?await sql`SELECT m.id,m.folio,m.movement_type::text type,CASE WHEN m.movement_type='TRANSFER' THEN t.status::text ELSE m.status::text END status,m.created_at,CASE WHEN m.movement_type='TRANSFER' THEN (t.origin_pos_registered_at IS NOT NULL AND t.destination_pos_registered_at IS NOT NULL) ELSE m.pos_registered_at IS NOT NULL END registered,CASE WHEN m.movement_type='TRANSFER' THEN ob.name||' → '||db.name ELSE b.name END branch,u.name user_name FROM inventory_movements m JOIN branches b ON b.id=m.branch_id JOIN users u ON u.id=m.created_by LEFT JOIN transfers t ON t.movement_id=m.id LEFT JOIN branches ob ON ob.id=t.origin_branch_id LEFT JOIN branches db ON db.id=t.destination_branch_id ORDER BY m.created_at DESC LIMIT 8`:branches.length===0?[]:await sql`SELECT m.id,m.folio,m.movement_type::text type,CASE WHEN m.movement_type='TRANSFER' THEN t.status::text ELSE m.status::text END status,m.created_at,CASE WHEN m.movement_type='TRANSFER' THEN (t.origin_pos_registered_at IS NOT NULL AND t.destination_pos_registered_at IS NOT NULL) ELSE m.pos_registered_at IS NOT NULL END registered,CASE WHEN m.movement_type='TRANSFER' THEN ob.name||' → '||db.name ELSE b.name END branch,u.name user_name FROM inventory_movements m JOIN branches b ON b.id=m.branch_id JOIN users u ON u.id=m.created_by LEFT JOIN transfers t ON t.movement_id=m.id LEFT JOIN branches ob ON ob.id=t.origin_branch_id LEFT JOIN branches db ON db.id=t.destination_branch_id WHERE (m.movement_type<>'TRANSFER' AND m.branch_id=ANY(${branches}::uuid[])) OR (m.movement_type='TRANSFER' AND (t.origin_branch_id=ANY(${branches}::uuid[]) OR t.destination_branch_id=ANY(${branches}::uuid[]))) ORDER BY m.created_at DESC LIMIT 8`;
  const statsRows=branches===null?await sql`SELECT count(*) FILTER(WHERE m.movement_type='RECEPTION' AND m.status::text='DRAFT')::int reception_in_progress,count(*) FILTER(WHERE m.movement_type='RECEPTION' AND m.status::text<>'DRAFT' AND m.created_at>=now()-interval '30 days')::int receptions_closed_30,count(*) FILTER(WHERE m.movement_type='EXIT' AND m.pos_registered_at IS NOT NULL AND m.created_at>=now()-interval '30 days')::int exits_registered_30,count(*) FILTER(WHERE m.created_at>=now()-interval '30 days')::int movements_30,count(*) FILTER(WHERE m.movement_type='TRANSFER' AND COALESCE(t.status::text,'') NOT IN ('COMPLETED','CANCELLED'))::int active_transfers FROM inventory_movements m LEFT JOIN transfers t ON t.movement_id=m.id`:branches.length===0?[{reception_in_progress:0,receptions_closed_30:0,exits_registered_30:0,movements_30:0,active_transfers:0}]:await sql`WITH a AS (SELECT m.*,t.status::text transfer_status FROM inventory_movements m LEFT JOIN transfers t ON t.movement_id=m.id WHERE (m.movement_type<>'TRANSFER' AND m.branch_id=ANY(${branches}::uuid[])) OR (m.movement_type='TRANSFER' AND (t.origin_branch_id=ANY(${branches}::uuid[]) OR t.destination_branch_id=ANY(${branches}::uuid[])))) SELECT count(*) FILTER(WHERE movement_type='RECEPTION' AND status::text='DRAFT')::int reception_in_progress,count(*) FILTER(WHERE movement_type='RECEPTION' AND status::text<>'DRAFT' AND created_at>=now()-interval '30 days')::int receptions_closed_30,count(*) FILTER(WHERE movement_type='EXIT' AND pos_registered_at IS NOT NULL AND created_at>=now()-interval '30 days')::int exits_registered_30,count(*) FILTER(WHERE created_at>=now()-interval '30 days')::int movements_30,count(*) FILTER(WHERE movement_type='TRANSFER' AND COALESCE(transfer_status,'') NOT IN ('COMPLETED','CANCELLED'))::int active_transfers FROM a`;
  const stats=statsRows[0]??{};
  const branchName=user.primaryBranchId?(await sql`SELECT name FROM branches WHERE id=${user.primaryBranchId}::uuid`)[0]?.name:null;
  const productRows=user.role==='MASTER'?await sql`SELECT count(*)::int n FROM products WHERE status::text='ACTIVE'`:[];
  const branchCount=branches===null?(await sql`SELECT count(*)::int n FROM branches WHERE status::text='ACTIVE'`)[0]?.n:branches.length;
  const firstName=user.name.split(/\s+/)[0]||user.name;
  return <div className="dashboardPage">
    <section className="dashHello"><div><h1>Hola, {firstName}</h1><p>{branchName?`Sucursal ${String(branchName)}`:user.role==='MASTER'?'Acceso global':'Sucursal asignada'}</p></div><div className="dashDate"><b>{dateFmt.format(new Date())}</b><span>Horario de Monterrey</span></div></section>
    <section className="dashHero"><div><span>CONTROL DE INVENTARIO</span><h2>Todo en orden,<br/>siempre en movimiento.</h2><i/></div><div className="heroCube">▱</div><small>TU MUNDO<br/>EN CONEXIÓN</small></section>
    <section className="dashStats" aria-label="Resumen operativo"><Link href="/entradas/nueva" className="statCard blue"><span className="statIcon">□</span><strong>{Number(stats.reception_in_progress??0).toLocaleString('es-MX')}</strong><small>Recepciones<br/>en proceso</small><b>›</b></Link><a href="#movimientos" className="statCard green"><span className="statIcon">✓</span><strong>{Number(stats.receptions_closed_30??0).toLocaleString('es-MX')}</strong><small>Recepciones cerradas<br/>(últimos 30 días)</small><b>›</b></a><Link href="/salidas/nueva" className="statCard red"><span className="statIcon">⇥</span><strong>{Number(stats.exits_registered_30??0).toLocaleString('es-MX')}</strong><small>Salidas registradas<br/>(últimos 30 días)</small><b>›</b></Link><Link href="/traspasos/nuevo" className="statCard slate"><span className="statIcon">⇄</span><strong>{Number(stats.active_transfers??0).toLocaleString('es-MX')}</strong><small>Traspasos<br/>activos</small><b>›</b></Link></section>
    <section className="operationGrid"><div className="operationPanel entryPanel"><div className="operationTitle"><span className="bigOpIcon">□</span><b>ENTRADA<br/>DE INVENTARIO</b><span>›</span></div><div className="operationLinks"><Link href="/entradas/nueva"><span>□</span><div><b>Recepción de Mercancía</b><small>Registro de mercancía nueva</small></div><i>›</i></Link><Link href="/devoluciones/nueva"><span>↩</span><div><b>Devoluciones</b><small>Mercado Libre, TikTok o cliente</small></div><i>›</i></Link></div></div><div className="operationPanel exitPanel"><div className="operationTitle"><span className="bigOpIcon">▣</span><b>SALIDA<br/>DE INVENTARIO</b><span>›</span></div><div className="operationLinks"><Link href="/salidas/nueva"><span>⇥</span><div><b>Nueva salida</b><small>Full o venta independiente</small></div><i>›</i></Link><Link href="/traspasos/nuevo"><span>⇄</span><div><b>Traspaso entre sucursales</b><small>Origen → destino</small></div><i>›</i></Link></div></div></section>
    <section id="movimientos" className="recentCard"><div className="sectionHeading"><h2>Movimientos recientes</h2><a href="#movimientos">Últimos {rows.length}</a></div><div className="movementHeader"><span>Folio</span><span>Tipo</span><span>Concepto</span><span>Estado</span><span>Fecha</span><span>Usuario</span></div><div className="movementList">{rows.length===0?<div className="emptyState">Aún no hay movimientos para mostrar.</div>:rows.map(r=>{const id=String(r.id),type=String(r.type),status=String(r.status);return <Link href={detail(id,type)} className="movementRow" key={id}><span className={`movementIcon ${type==='EXIT'?'out':type==='TRANSFER'?'transfer':'in'}`}>{typeIcon(type)}</span><span className="movementFolio"><b>{String(r.folio)}</b><small>{String(r.branch)}</small></span><span className={`typePill ${type==='EXIT'?'out':type==='TRANSFER'?'transfer':'in'}`}>{typeShort(type)}</span><span className="movementConcept">{typeLabel(type)}</span><span className={`statusPill ${statusTone(status)}`}>{statusLabel(status)}</span><span className="movementDate">{fmt.format(new Date(String(r.created_at)))}</span><span className="movementUser">{String(r.user_name)}</span></Link>})}</div></section>
    <section className="inventoryStrip"><div><span className="bars">▂▅▇</span><p><b>Inventario en movimiento</b><small>Últimos 30 días</small></p></div><div><strong>{Number(stats.movements_30??0).toLocaleString('es-MX')}</strong><small>Movimientos</small></div>{user.role==='MASTER'&&<div><strong>{Number(productRows[0]?.n??0).toLocaleString('es-MX')}</strong><small>Tipos de producto</small></div>}<div><strong>{Number(branchCount??0).toLocaleString('es-MX')}</strong><small>Sucursales</small></div></section>
  </div>
}
