"use client";
import { useState } from "react";
import type { AppRole } from "@/lib/auth/types";
export type ReceptionLine={id:string;colorId:string;model:string;quantity:number;color:string};
export type ReceptionBox={id:string;box_number:number;status:string;lines:ReceptionLine[]};
export type ReceptionMovement={id:string;folio:string;branch_id:string;branch:string;status:string;pos_registered_at:string|null;current_version:number;expected_boxes:number;product_id:string|null;product_name:string|null};

export default function ReceptionEditor({movement,boxes,colors,role}:{movement:ReceptionMovement;boxes:ReceptionBox[];colors:Array<{id:string;name:string}>;role:AppRole}){
  const [box,setBox]=useState(boxes[0]?.id);
  const selected=boxes.find(b=>b.id===box)||boxes[0];
  const editable=movement.status==='DRAFT'||(role==='MASTER'&&movement.status!=='CANCELLED');
  const total=boxes.reduce((sum,b)=>sum+b.lines.reduce((s,l)=>s+Number(l.quantity),0),0);
  const lineCount=boxes.reduce((sum,b)=>sum+b.lines.length,0);
  const closedCount=boxes.filter(b=>b.status==='CLOSED').length;
  const draftCount=boxes.filter(b=>b.status!=='CLOSED'&&b.lines.length>0).length;
  const untouchedCount=boxes.filter(b=>b.status!=='CLOSED'&&b.lines.length===0).length;
  const progress=movement.expected_boxes?Math.round((closedCount/movement.expected_boxes)*100):0;
  async function act(body:Record<string,unknown>,confirmText?:string){if(confirmText&&!confirm(confirmText))return;const r=await fetch('/api/receptions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({movementId:movement.id,...body})});const j=await r.json() as {error?:string};if(!r.ok)alert(j.error||'ERROR');else location.reload()}
  const closeSummary=`Resumen de cierre:\n${boxes.length} cajas · ${lineCount} líneas · ${total} piezas\n${closedCount} de ${movement.expected_boxes} cajas cerradas.\n\nAl cerrar, MANAGER y OPERATIVE ya no podrán modificar. ¿Continuar?`;
  const posPending=movement.status==='POS_CORRECTION_PENDING'||(movement.status!=='DRAFT'&&!movement.pos_registered_at);
  const boxEditable=editable&&(movement.status!=='DRAFT'||selected?.status!=='CLOSED');
  return <>
    <header className="receptionHeader"><div><h1>{movement.folio}</h1><p>{movement.branch} · {movement.status} · versión {movement.current_version}</p><strong className="receptionProduct">{movement.product_name||'Producto histórico sin asignar'}</strong></div><div className="actions">{editable&&<button onClick={()=>act({action:'addBox'})}>+ Caja</button>}{movement.status==='DRAFT'&&<button className="primary" disabled={closedCount!==movement.expected_boxes} onClick={()=>act({action:'close'},closeSummary)}>Cerrar recepción</button>}{posPending&&<button className="primary" onClick={()=>act({action:'pos'},'Confirmar REGISTRADO EN SISTEMA para esta versión. Esta acción queda auditada.')}>Registrado en sistema</button>}{movement.status!=='DRAFT'&&<a className="buttonLink" href={`/api/receptions/${movement.id}/detail?version=${movement.current_version}`}>Detalle por Caja</a>}</div></header>
    <section className="card pad receptionProgress"><div className="progressTop"><div><b>{closedCount} de {movement.expected_boxes} cajas completadas</b><small>{progress}% completado</small></div><strong>{total} pzas.</strong></div><div className="progressTrack"><span style={{width:`${progress}%`}}/></div><div className="boxLegend"><span className="legendClosed">● Cerradas ({closedCount})</span><span className="legendDraft">● Borrador ({draftCount})</span><span className="legendEmpty">● Sin contar ({untouchedCount})</span></div></section>
    <section className="boxBoard" aria-label="Cajas de la recepción">{boxes.map(b=>{const state=b.status==='CLOSED'?'closed':b.lines.length?'draft':'empty';return <button type="button" className={`boxTile ${state} ${b.id===selected?.id?'active':''}`} onClick={()=>setBox(b.id)} key={b.id}><b>{b.box_number}</b><small>{state==='closed'?'Cerrada':state==='draft'?'Borrador':'Sin contar'}</small></button>})}</section>
    {selected&&<section className="card pad receptionBox"><div className="boxTitle"><div><h2>Caja {selected.box_number} de {movement.expected_boxes}</h2><p>{movement.product_name}</p></div><span className={`boxState ${selected.status==='CLOSED'?'closed':selected.lines.length?'draft':'empty'}`}>{selected.status==='CLOSED'?'Cerrada':selected.lines.length?'Borrador':'Sin contar'}</span></div><div className="lines">{selected.lines.map(l=><div className="line" key={l.id}><div><b>{l.model}</b><small>{l.color}</small></div>{boxEditable?<form className="inline" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:'saveLine',lineId:l.id,boxId:selected.id,colorId:l.colorId,modelReference:l.model,quantity:Number(f.get('quantity'))})}}><input aria-label="Cantidad" name="quantity" type="number" min="1" step="1" defaultValue={l.quantity} required/><button>Guardar</button><button type="button" onClick={()=>act({action:'deleteLine',lineId:l.id},'¿Eliminar esta línea?')}>Eliminar</button></form>:<strong>{l.quantity}</strong>}</div>)}</div>{boxEditable&&<form className="capture receptionCapture" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:'saveLine',boxId:selected.id,colorId:f.get('color'),modelReference:f.get('model'),quantity:Number(f.get('quantity'))})}}><label>Color<select name="color" required defaultValue=""><option value="" disabled>Selecciona color…</option>{colors.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Modelo<input name="model" placeholder="MODELO" autoCapitalize="characters" required/></label><label>Cantidad<input name="quantity" type="number" min="1" step="1" inputMode="numeric" placeholder="CANT." required/></label><button className="primary">Agregar línea</button></form>}{movement.status==='DRAFT'&&selected.status!=='CLOSED'&&<button className="closeBoxButton" disabled={selected.lines.length===0} onClick={()=>act({action:'closeBox',boxId:selected.id},`¿Cerrar Caja ${selected.box_number}? Después ya no podrá editarse durante el borrador de la recepción.`)}>Cerrar conteo de Caja {selected.box_number}</button>}</section>}
  </>;
}
