import Link from "next/link";
import { requireUser,getAuthorizedBranchIds } from "@/lib/auth/authorization";
import { sql } from "@/lib/db";

type Row={id:string;folio:string;product_name:string;branch_name:string;shipping_method:string;expected_boxes:number;received_boxes:number;closed_boxes:number;created_at:string;last_received_at:string|null;status:string};

function ShipmentCard({r}:{r:Row}){const received=Number(r.received_boxes);const expected=Number(r.expected_boxes);const counted=Number(r.closed_boxes);const method=r.shipping_method==='PENDING'?'Método pendiente':r.shipping_method;return <Link href={`/entradas/${r.id}`} className="shipmentCard"><div className="shipmentTop"><div><h3>{r.product_name}</h3><small>{method} · {r.branch_name}</small></div><span>›</span></div><div className="shipmentProgress"><div><b>{received} de {expected}</b><small> cajas recibidas</small></div><div><b>{counted} de {received}</b><small> recibidas contadas</small></div></div><div className="shipmentBar"><i style={{width:`${expected?Math.round(received/expected*100):0}%`}}/></div><div className="shipmentMeta"><span>{r.last_received_at?`Última llegada: ${new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Monterrey'}).format(new Date(r.last_received_at))}`:'Aún sin llegada registrada'}</span><small>{r.folio}</small></div></Link>}

function Group({title,subtitle,rows,tone,collapsed=false}:{title:string;subtitle:string;rows:Row[];tone:string;collapsed?:boolean}){const body=<>{rows.length?rows.map(r=><ShipmentCard key={r.id} r={r}/>):<div className="shipmentEmpty">No hay embarques en este grupo.</div>}</>;if(collapsed)return <details className={`shipmentGroup ${tone}`}><summary><div><b>{title}</b><small>{subtitle}</small></div><span>{rows.length}</span></summary><div className="shipmentList">{body}</div></details>;return <section className={`shipmentGroup ${tone}`}><div className="shipmentGroupHead"><div><b>{title}</b><small>{subtitle}</small></div><span>{rows.length}</span></div><div className="shipmentList">{body}</div></section>}

export default async function ReceptionsPage(){const u=await requireUser();const ids=await getAuthorizedBranchIds(u);const rows=(ids===null?await sql`SELECT m.id::text,m.folio,p.name AS product_name,br.name AS branch_name,r.shipping_method,r.expected_boxes,count(b.id) FILTER(WHERE b.received_at IS NOT NULL)::int AS received_boxes,count(b.id) FILTER(WHERE b.received_at IS NOT NULL AND b.status::text='CLOSED')::int AS closed_boxes,m.created_at,max(b.received_at) AS last_received_at,m.status::text AS status FROM inventory_movements m JOIN receptions r ON r.movement_id=m.id JOIN products p ON p.id=r.product_id JOIN branches br ON br.id=m.branch_id LEFT JOIN reception_boxes b ON b.reception_id=r.id WHERE m.movement_type='RECEPTION' AND m.status::text<>'CANCELLED' GROUP BY m.id,m.folio,p.name,br.name,r.shipping_method,r.expected_boxes,m.created_at,m.status ORDER BY m.created_at DESC`:ids.length?await sql`SELECT m.id::text,m.folio,p.name AS product_name,br.name AS branch_name,r.shipping_method,r.expected_boxes,count(b.id) FILTER(WHERE b.received_at IS NOT NULL)::int AS received_boxes,count(b.id) FILTER(WHERE b.received_at IS NOT NULL AND b.status::text='CLOSED')::int AS closed_boxes,m.created_at,max(b.received_at) AS last_received_at,m.status::text AS status FROM inventory_movements m JOIN receptions r ON r.movement_id=m.id JOIN products p ON p.id=r.product_id JOIN branches br ON br.id=m.branch_id LEFT JOIN reception_boxes b ON b.reception_id=r.id WHERE m.movement_type='RECEPTION' AND m.branch_id=ANY(${ids}::uuid[]) AND m.status::text<>'CANCELLED' GROUP BY m.id,m.folio,p.name,br.name,r.shipping_method,r.expected_boxes,m.created_at,m.status ORDER BY m.created_at DESC`:[]) as unknown as Row[];const pending=rows.filter(r=>Number(r.received_boxes)<Number(r.expected_boxes));const counting=rows.filter(r=>Number(r.received_boxes)===Number(r.expected_boxes)&&Number(r.closed_boxes)<Number(r.received_boxes));const completed=rows.filter(r=>Number(r.received_boxes)===Number(r.expected_boxes)&&Number(r.closed_boxes)===Number(r.received_boxes));const attention=pending.length+counting.length;return <main className="shipmentsPage"><div className="shipmentsTitle"><div><h1>Recepción de mercancía</h1><p>{attention?`${attention} embarque${attention===1?'':'s'} requieren atención`:'Todo al día'}</p></div><Link className="shipmentNew" href="/entradas/nueva">+ Nuevo</Link></div><Group title="Pendientes de recibir" subtitle="Todavía faltan cajas por llegar" rows={pending} tone="pending"/><Group title="Recibidos · pendientes de conteo" subtitle="Ya llegaron; falta terminar el conteo" rows={counting} tone="counting"/><Group title="Completados" subtitle="Recepción y conteo terminados" rows={completed} tone="complete" collapsed/></main>}
