import "server-only";
import type { PoolClient } from "@neondatabase/serverless";
import { withTransaction } from "@/lib/db";
import { assertBranchAccess } from "@/lib/auth/authorization";
import type { SessionUser } from "@/lib/auth/types";
import { assertPositiveQuantity,canEditReception,canRegisterPos,canRegisterPosCorrection,type MovementStatus } from "./policy";
export type ExitChannel="MERCADO_LIBRE"|"TIKTOK";export type ExitType="FULL"|"INDEPENDENT_SALE";type M={id:string;branch_id:string;status:MovementStatus;pos_registered_at:string|null;current_version:number};
async function lock(c:PoolClient,u:SessionUser,id:string){const q=await c.query<M>("SELECT id::text,branch_id::text,status::text AS status,pos_registered_at,current_version FROM inventory_movements WHERE id=$1::uuid AND movement_type='EXIT' FOR UPDATE",[id]);const m=q.rows[0];if(!m)throw new Error('NOT_FOUND');await assertBranchAccess(u,m.branch_id);return m}
async function snap(c:PoolClient,id:string){const q=await c.query<{snapshot:Record<string,unknown>;total:number}>(`SELECT jsonb_build_object('movement',to_jsonb(m),'exit',to_jsonb(e),'lines',COALESCE((SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object('product_name',p.name) ORDER BY l.created_at,l.id) FROM exit_lines l JOIN products p ON p.id=l.product_id WHERE l.movement_id=m.id),'[]'::jsonb)) snapshot,COALESCE((SELECT sum(quantity)::int FROM exit_lines WHERE movement_id=m.id),0)::int total FROM inventory_movements m JOIN exits e ON e.movement_id=m.id WHERE m.id=$1::uuid`,[id]);if(!q.rows[0])throw new Error('NOT_FOUND');return q.rows[0]}
async function correction(c:PoolClient,u:SessionUser,m:M,before:Awaited<ReturnType<typeof snap>>,action:string){const q=await c.query<{current_version:number}>("UPDATE inventory_movements SET current_version=current_version+1,updated_at=now(),status=CASE WHEN pos_registered_at IS NULL THEN status ELSE 'POS_CORRECTION_PENDING'::movement_status END WHERE id=$1 RETURNING current_version",[m.id]);const v=q.rows[0].current_version,after=await snap(c,m.id);await c.query("INSERT INTO movement_versions(movement_id,version,snapshot,created_by) VALUES($1,$2,$3::jsonb,$4)",[m.id,v,JSON.stringify(after.snapshot),u.id]);await c.query("INSERT INTO movement_change_sets(movement_id,from_version,to_version,previous_total,new_total,quantity_difference,changes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8)",[m.id,v-1,v,before.total,after.total,after.total-before.total,JSON.stringify([{action}]),u.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action,previous_value,new_value) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb)",[u.id,m.branch_id,m.id,action,JSON.stringify(before.snapshot),JSON.stringify(after.snapshot)])}
export async function createExit(u:SessionUser,branchId:string,channel:ExitChannel,exitType:ExitType){await assertBranchAccess(u,branchId);if(!['MERCADO_LIBRE','TIKTOK'].includes(channel))throw new Error('INVALID_CHANNEL');if(!['FULL','INDEPENDENT_SALE'].includes(exitType))throw new Error('INVALID_EXIT_TYPE');return withTransaction(async c=>{const folio=`SAL-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const q=await c.query<{id:string}>("INSERT INTO inventory_movements(folio,movement_type,branch_id,created_by) VALUES($1,'EXIT',$2,$3) RETURNING id::text",[folio,branchId,u.id]);await c.query("INSERT INTO exits(movement_id,channel,exit_type) VALUES($1,$2::exit_channel,$3::exit_type)",[q.rows[0].id,channel,exitType]);return q.rows[0].id})}
export async function saveExitLine(u:SessionUser,id:string,x:{lineId?:string;productId:string;quantity:number}){assertPositiveQuantity(x.quantity);return withTransaction(async c=>{const m=await lock(c,u,id);if(!canEditReception(u.role,m.status))throw new Error('LOCKED');const before=m.status==='DRAFT'?null:await snap(c,id);const valid=await c.query("SELECT 1 FROM products WHERE id=$1 AND status='ACTIVE'",[x.productId]);if(!valid.rowCount)throw new Error('INVALID_PRODUCT');if(x.lineId){const q=await c.query("UPDATE exit_lines SET product_id=$1,quantity=$2 WHERE id=$3 AND movement_id=$4",[x.productId,x.quantity,x.lineId,id]);if(!q.rowCount)throw new Error('LINE_NOT_FOUND')}else await c.query("INSERT INTO exit_lines(movement_id,product_id,quantity) VALUES($1,$2,$3)",[id,x.productId,x.quantity]);if(before)await correction(c,u,m,before,'MASTER_EXIT_EDIT')})}
export async function deleteExitLine(u:SessionUser,id:string,lineId:string){return withTransaction(async c=>{const m=await lock(c,u,id);if(!canEditReception(u.role,m.status))throw new Error('LOCKED');const before=m.status==='DRAFT'?null:await snap(c,id);const q=await c.query("DELETE FROM exit_lines WHERE id=$1 AND movement_id=$2",[lineId,id]);if(!q.rowCount)throw new Error('LINE_NOT_FOUND');if(before)await correction(c,u,m,before,'MASTER_EXIT_DELETE')})}
export async function closeExit(u:SessionUser,id:string){return withTransaction(async c=>{const m=await lock(c,u,id);if(m.status!=='DRAFT')throw new Error('ALREADY_CLOSED');const q=await c.query<{n:number}>("SELECT count(*)::int n FROM exit_lines WHERE movement_id=$1",[id]);if(q.rows[0].n<1)throw new Error('EXIT_WITHOUT_LINES');await c.query("UPDATE inventory_movements SET status='CLOSED',closed_by=$1,closed_at=now(),updated_at=now() WHERE id=$2",[u.id,id]);const s=await snap(c,id);await c.query("INSERT INTO movement_versions(movement_id,version,snapshot,created_by) VALUES($1,1,$2::jsonb,$3) ON CONFLICT DO NOTHING",[id,JSON.stringify(s.snapshot),u.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action,new_value) VALUES($1,$2,$3,'EXIT_CLOSED',$4::jsonb)",[u.id,m.branch_id,id,JSON.stringify(s.snapshot)])})}
export async function registerExitPos(u:SessionUser,id:string){return withTransaction(async c=>{const m=await lock(c,u,id),corr=canRegisterPosCorrection(m.status,m.pos_registered_at);if(!corr&&!canRegisterPos(m.status,m.pos_registered_at))throw new Error('POS_NOT_ALLOWED');await c.query("UPDATE inventory_movements SET status=$1::movement_status,pos_registered_by=$2,pos_registered_at=now(),updated_at=now() WHERE id=$3",[corr?'POS_RECONCILED':'POS_REGISTERED',u.id,id]);await c.query("INSERT INTO pos_registration_events(movement_id,branch_id,event_type,movement_version,user_id) VALUES($1,$2,$3::pos_event_type,$4,$5)",[id,m.branch_id,corr?'CORRECTION':'INITIAL',m.current_version,u.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action) VALUES($1,$2,$3,$4)",[u.id,m.branch_id,id,corr?'EXIT_POS_CORRECTION_REGISTERED':'EXIT_POS_REGISTERED'])})}
