import "server-only";
import { sql } from "@/lib/db";
import type { SessionUser } from "@/lib/auth/types";
const master=(u:SessionUser)=>{if(u.role!=="MASTER") throw new Error("MASTER_REQUIRED")};
const cleanHex=(value?:string|null)=>{const v=(value||'').trim().toUpperCase();if(!v)return null;if(!/^#[0-9A-F]{6}$/.test(v))throw new Error("HEX_INVALID");return v};
async function colorHexSupported(){const r=await sql`SELECT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='product_colors' AND column_name='hex_color') AS ok`;return Boolean(r[0]?.ok)}
export async function listProducts(){return sql`SELECT p.id::text,p.name,p.status::text,COALESCE(jsonb_agg(jsonb_build_object('id',c.id::text,'name',c.name,'status',c.status::text,'hex',to_jsonb(c)->>'hex_color') ORDER BY c.name) FILTER(WHERE c.id IS NOT NULL),'[]'::jsonb) colors FROM products p LEFT JOIN product_colors c ON c.product_id=p.id GROUP BY p.id ORDER BY p.name`;}
export async function createProduct(u:SessionUser,name:string){master(u);const n=name.trim();if(!n)throw new Error("NAME_REQUIRED");return sql`INSERT INTO products(name) VALUES(${n}) RETURNING id::text`;}
export async function renameProduct(u:SessionUser,id:string,name:string){master(u);const n=name.trim();if(!n)throw new Error("NAME_REQUIRED");await sql`UPDATE products SET name=${n},updated_at=now() WHERE id=${id}::uuid`;}
export async function setProductStatus(u:SessionUser,id:string,status:"ACTIVE"|"INACTIVE"){master(u);await sql`UPDATE products SET status=${status}::record_status,updated_at=now() WHERE id=${id}::uuid`;}
export async function createColor(u:SessionUser,productId:string,name:string,hex?:string|null){master(u);const n=name.trim();if(!n)throw new Error("NAME_REQUIRED");const h=cleanHex(hex);const rows=await sql`INSERT INTO product_colors(product_id,name) VALUES(${productId}::uuid,${n}) RETURNING id::text`;if(h&&await colorHexSupported())await sql`UPDATE product_colors SET hex_color=${h},updated_at=now() WHERE id=${rows[0].id}::uuid`;return rows;}
export async function renameColor(u:SessionUser,id:string,name:string,hex?:string|null){master(u);const n=name.trim();if(!n)throw new Error("NAME_REQUIRED");const h=cleanHex(hex);await sql`UPDATE product_colors SET name=${n},updated_at=now() WHERE id=${id}::uuid`;if(await colorHexSupported())await sql`UPDATE product_colors SET hex_color=${h},updated_at=now() WHERE id=${id}::uuid`;}
export async function setColorStatus(u:SessionUser,id:string,status:"ACTIVE"|"INACTIVE"){master(u);await sql`UPDATE product_colors SET status=${status}::record_status,updated_at=now() WHERE id=${id}::uuid`;}
