import "server-only";
import { sql } from "@/lib/db";
import { assertBranchAccess } from "@/lib/auth/authorization";
import type { SessionUser } from "@/lib/auth/types";
import { assertPositiveQuantity, canEditReception, canRegisterPos, type MovementStatus } from "./policy";

async function movement(user: SessionUser, id: string) { const rows=await sql`SELECT id::text,branch_id::text,status::text,pos_registered_at,current_version FROM inventory_movements WHERE id=${id}::uuid AND movement_type::text='RECEPTION' LIMIT 1`; const m=rows[0]; if(!m) throw new Error("NOT_FOUND"); await assertBranchAccess(user,String(m.branch_id)); return m; }
export async function createReception(user:SessionUser,branchId:string,expectedBoxes:number){ await assertBranchAccess(user,branchId); if(!Number.isInteger(expectedBoxes)||expectedBoxes<1) throw new Error("INVALID_BOX_COUNT"); const folio=`REC-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`; const rows=await sql`WITH m AS (INSERT INTO inventory_movements(folio,movement_type,branch_id,created_by) VALUES(${folio},'RECEPTION',${branchId}::uuid,${user.id}::uuid) RETURNING id), r AS (INSERT INTO receptions(movement_id,expected_boxes) SELECT id,${expectedBoxes} FROM m RETURNING id,movement_id) INSERT INTO reception_boxes(reception_id,box_number,status) SELECT r.id,g,'DRAFT' FROM r CROSS JOIN generate_series(1,${expectedBoxes}) g RETURNING (SELECT movement_id::text FROM r) movement_id`; return String(rows[0].movement_id); }
export async function addBox(user:SessionUser,movementId:string){ const m=await movement(user,movementId); if(!canEditReception(user.role,m.status as MovementStatus)) throw new Error("LOCKED"); const rows=await sql`UPDATE receptions SET expected_boxes=expected_boxes+1 WHERE movement_id=${movementId}::uuid RETURNING id,expected_boxes`; const r=rows[0]; await sql`INSERT INTO reception_boxes(reception_id,box_number,status) VALUES(${String(r.id)}::uuid,${Number(r.expected_boxes)},'DRAFT')`; }
export async function upsertLine(user:SessionUser,movementId:string,input:{lineId?:string,boxId:string,productId:string,colorId:string,modelReference:string,quantity:number}){ const m=await movement(user,movementId); if(!canEditReception(user.role,m.status as MovementStatus)) throw new Error("LOCKED"); assertPositiveQuantity(input.quantity); const valid=await sql`SELECT 1 FROM reception_boxes b JOIN receptions r ON r.id=b.reception_id JOIN product_colors c ON c.id=${input.colorId}::uuid AND c.product_id=${input.productId}::uuid AND c.status::text='ACTIVE' JOIN products p ON p.id=c.product_id AND p.status::text='ACTIVE' WHERE b.id=${input.boxId}::uuid AND r.movement_id=${movementId}::uuid`; if(!valid[0]) throw new Error("INVALID_PRODUCT_COLOR"); const model=input.modelReference.trim(); if(!model) throw new Error("MODEL_REQUIRED"); if(input.lineId) await sql`UPDATE reception_box_lines SET product_id=${input.productId}::uuid,color_id=${input.colorId}::uuid,model_reference=${model},quantity=${input.quantity},updated_at=now() WHERE id=${input.lineId}::uuid AND box_id=${input.boxId}::uuid`; else await sql`INSERT INTO reception_box_lines(box_id,product_id,color_id,model_reference,quantity) VALUES(${input.boxId}::uuid,${input.productId}::uuid,${input.colorId}::uuid,${model},${input.quantity})`; if(m.status!=="DRAFT") await versionAfterClosed(user,movementId,"MASTER_POST_CLOSE_EDIT"); }
export async function deleteLine(user:SessionUser,movementId:string,lineId:string){ const m=await movement(user,movementId); if(!canEditReception(user.role,m.status as MovementStatus)) throw new Error("LOCKED"); await sql`DELETE FROM reception_box_lines l USING reception_boxes b,receptions r WHERE l.id=${lineId}::uuid AND l.box_id=b.id AND b.reception_id=r.id AND r.movement_id=${movementId}::uuid`; if(m.status!=="DRAFT") await versionAfterClosed(user,movementId,"MASTER_POST_CLOSE_DELETE"); }
async function snapshot(id:string){ const rows=await sql`SELECT jsonb_build_object('movement',to_jsonb(m),'reception',to_jsonb(r),'boxes',COALESCE((SELECT jsonb_agg(jsonb_build_object('box',to_jsonb(b),'lines',COALESCE((SELECT jsonb_agg(to_jsonb(l) ORDER BY l.created_at) FROM reception_box_lines l WHERE l.box_id=b.id),'[]'::jsonb)) ORDER BY b.box_number) FROM reception_boxes b WHERE b.reception_id=r.id),'[]'::jsonb)) snap, COALESCE((SELECT sum(l.quantity)::int FROM reception_box_lines l JOIN reception_boxes b ON b.id=l.box_id WHERE b.reception_id=r.id),0)::int total FROM inventory_movements m JOIN receptions r ON r.movement_id=m.id WHERE m.id=${id}::uuid`; return rows[0]; }
async function versionAfterClosed(user:SessionUser,id:string,action:string){ const before=await snapshot(id); const rows=await sql`UPDATE inventory_movements SET current_version=current_version+1,updated_at=now() WHERE id=${id}::uuid RETURNING current_version,branch_id`; const v=Number(rows[0].current_version); const after=await snapshot(id); await sql`INSERT INTO movement_versions(movement_id,version,snapshot,created_by) VALUES(${id}::uuid,${v},${JSON.stringify(after.snap)}::jsonb,${user.id}::uuid)`; await sql`INSERT INTO movement_change_sets(movement_id,from_version,to_version,previous_total,new_total,quantity_difference,changes,created_by) VALUES(${id}::uuid,${v-1},${v},${Number(before.total)},${Number(after.total)},${Number(after.total)-Number(before.total)},${JSON.stringify([{action}])}::jsonb,${user.id}::uuid)`; await sql`INSERT INTO audit_events(user_id,branch_id,movement_id,action,new_value) VALUES(${user.id}::uuid,${String(rows[0].branch_id)}::uuid,${id}::uuid,${action},${JSON.stringify(after.snap)}::jsonb)`; }
export async function closeReception(user:SessionUser,id:string){ const m=await movement(user,id); if(m.status!=="DRAFT") throw new Error("ALREADY_CLOSED"); const check=await sql`SELECT r.expected_boxes,count(DISTINCT b.id)::int boxes,count(l.id)::int lines,COALESCE(sum(l.quantity),0)::int total FROM receptions r JOIN reception_boxes b ON b.reception_id=r.id LEFT JOIN reception_box_lines l ON l.box_id=b.id WHERE r.movement_id=${id}::uuid GROUP BY r.expected_boxes`; const c=check[0]; if(!c||Number(c.boxes)!==Number(c.expected_boxes)||Number(c.lines)<1) throw new Error("INCOMPLETE_RECEPTION"); await sql`UPDATE reception_boxes SET status='CLOSED',closed_by=${user.id}::uuid,closed_at=now() WHERE reception_id=(SELECT id FROM receptions WHERE movement_id=${id}::uuid)`; await sql`UPDATE inventory_movements SET status='CLOSED',closed_by=${user.id}::uuid,closed_at=now(),updated_at=now() WHERE id=${id}::uuid`; const s=await snapshot(id); await sql`INSERT INTO movement_versions(movement_id,version,snapshot,created_by) VALUES(${id}::uuid,1,${JSON.stringify(s.snap)}::jsonb,${user.id}::uuid) ON CONFLICT(movement_id,version) DO NOTHING`; await sql`INSERT INTO audit_events(user_id,branch_id,movement_id,action,new_value) VALUES(${user.id}::uuid,${String(m.branch_id)}::uuid,${id}::uuid,'RECEPTION_CLOSED',${JSON.stringify(s.snap)}::jsonb)`; }
export async function registerPos(user:SessionUser,id:string){ const m=await movement(user,id); if(!canRegisterPos(m.status as MovementStatus,m.pos_registered_at)) throw new Error("POS_NOT_ALLOWED"); await sql`UPDATE inventory_movements SET status='POS_REGISTERED',pos_registered_by=${user.id}::uuid,pos_registered_at=now(),updated_at=now() WHERE id=${id}::uuid`; await sql`INSERT INTO pos_registration_events(movement_id,branch_id,event_type,movement_version,user_id) VALUES(${id}::uuid,${String(m.branch_id)}::uuid,'INITIAL',${Number(m.current_version)},${user.id}::uuid)`; await sql`INSERT INTO audit_events(user_id,branch_id,movement_id,action) VALUES(${user.id}::uuid,${String(m.branch_id)}::uuid,${id}::uuid,'POS_REGISTERED')`; }
