import "server-only";
import type { PoolClient } from "@neondatabase/serverless";
import { withTransaction } from "@/lib/db";
import { assertBranchAccess } from "@/lib/auth/authorization";
import type { SessionUser } from "@/lib/auth/types";
import { assertPositiveQuantity,canEditReception,canRegisterPos,canRegisterPosCorrection,type MovementStatus } from "./policy";
export type ReturnOrigin="RETURN_ML"|"RETURN_TIKTOK"|"RETURN_CUSTOMER";export type ReturnCondition="GOOD"|"DAMAGED";
type M={id:string;branch_id:string;status:MovementStatus;pos_registered_at:string|null;current_version:number};
async function lock(c:PoolClient,u:SessionUser,id:string){const q=await c.query<M>("SELECT id::text,branch_id::text,status::text AS status,pos_registered_at,current_version FROM inventory_movements WHERE id=$1::uuid AND movement_type IN ('RETURN_ML','RETURN_TIKTOK','RETURN_CUSTOMER') FOR UPDATE",[id]);const m=q.rows[0];if(!m)throw new Error('NOT_FOUND');await assertBranchAccess(u,m.branch_id);return m}
async function snap(c:PoolClient,id:string){const q=await c.query<{snapshot:Record<string,unknown>;total:number}>(`SELECT jsonb_build_object('movement',to_jsonb(m),'header',to_jsonb(h),'lines',COALESCE((SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object('product_name',p.name,'color_name',pc.name) ORDER BY l.created_at,l.id) FROM return_lines l JOIN products p ON p.id=l.product_id JOIN product_colors pc ON pc.id=l.color_id WHERE l.movement_id=m.id),'[]'::jsonb),'evidence',COALESCE((SELECT jsonb_agg(to_jsonb(e) ORDER BY e.slot) FROM return_evidence e WHERE e.movement_id=m.id),'[]'::jsonb)) snapshot,COALESCE((SELECT sum(quantity)::int FROM return_lines WHERE movement_id=m.id),0)::int total FROM inventory_movements m JOIN return_headers h ON h.movement_id=m.id WHERE m.id=$1::uuid`,[id]);if(!q.rows[0])throw new Error('NOT_FOUND');return q.rows[0]}
async function correction(c:PoolClient,u:SessionUser,m:M,before:Awaited<ReturnType<typeof snap>>,action:string){const q=await c.query<{current_version:number}>("UPDATE inventory_movements SET current_version=current_version+1,updated_at=now(),status=CASE WHEN pos_registered_at IS NULL THEN status ELSE 'POS_CORRECTION_PENDING'::movement_status END WHERE id=$1 RETURNING current_version",[m.id]);const v=q.rows[0].current_version,after=await snap(c,m.id);await c.query("INSERT INTO movement_versions(movement_id,version,snapshot,created_by) VALUES($1,$2,$3::jsonb,$4)",[m.id,v,JSON.stringify(after.snapshot),u.id]);await c.query("INSERT INTO movement_change_sets(movement_id,from_version,to_version,previous_total,new_total,quantity_difference,changes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8)",[m.id,v-1,v,before.total,after.total,after.total-before.total,JSON.stringify([{action}]),u.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action,previous_value,new_value) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb)",[u.id,m.branch_id,m.id,action,JSON.stringify(before.snapshot),JSON.stringify(after.snapshot)])}
export async function createReturn(u:SessionUser,branchId:string,origin:ReturnOrigin){await assertBranchAccess(u,branchId);if(!['RETURN_ML','RETURN_TIKTOK','RETURN_CUSTOMER'].includes(origin))throw new Error('INVALID_ORIGIN');return withTransaction(async c=>{const folio=`DEV-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const q=await c.query<{id:string}>("INSERT INTO inventory_movements(folio,movement_type,branch_id,created_by) VALUES($1,$2::movement_type,$3,$4) RETURNING id::text",[folio,origin,branchId,u.id]);await c.query("INSERT INTO return_headers(movement_id) VALUES($1)",[q.rows[0].id]);return q.rows[0].id})}
export async function saveReturnLine(u:SessionUser,id:string,x:{lineId?:string;productId:string;colorId:string;modelReference:string;quantity:number;condition:ReturnCondition;reason:string}){assertPositiveQuantity(x.quantity);const model=x.modelReference.trim().toUpperCase(),reason=x.reason.trim();if(!model)throw new Error('MODEL_REQUIRED');if(!['GOOD','DAMAGED'].includes(x.condition))throw new Error('INVALID_CONDITION');if(x.condition==='DAMAGED'&&!reason)throw new Error('REASON_REQUIRED');return withTransaction(async c=>{const m=await lock(c,u,id);if(!canEditReception(u.role,m.status))throw new Error('LOCKED');const before=m.status==='DRAFT'?null:await snap(c,id);const valid=await c.query("SELECT 1 FROM product_colors pc JOIN products p ON p.id=pc.product_id WHERE pc.id=$1 AND pc.product_id=$2 AND pc.status='ACTIVE' AND p.status='ACTIVE'",[x.colorId,x.productId]);if(!valid.rowCount)throw new Error('INVALID_PRODUCT_COLOR');if(x.lineId){const q=await c.query("UPDATE return_lines SET product_id=$1,color_id=$2,model_reference=$3,quantity=$4,condition=$5::return_condition,return_reason=$6 WHERE id=$7 AND movement_id=$8",[x.productId,x.colorId,model,x.quantity,x.condition,x.condition==='GOOD'?'':reason,x.lineId,id]);if(!q.rowCount)throw new Error('LINE_NOT_FOUND')}else await c.query("INSERT INTO return_lines(movement_id,product_id,color_id,model_reference,quantity,condition,return_reason) VALUES($1,$2,$3,$4,$5,$6::return_condition,$7)",[id,x.productId,x.colorId,model,x.quantity,x.condition,x.condition==='GOOD'?'':reason]);if(before)await correction(c,u,m,before,'MASTER_RETURN_EDIT')})}
export async function deleteReturnLine(u:SessionUser,id:string,lineId:string){return withTransaction(async c=>{const m=await lock(c,u,id);if(!canEditReception(u.role,m.status))throw new Error('LOCKED');const before=m.status==='DRAFT'?null:await snap(c,id);const q=await c.query("DELETE FROM return_lines WHERE id=$1 AND movement_id=$2",[lineId,id]);if(!q.rowCount)throw new Error('LINE_NOT_FOUND');if(before)await correction(c,u,m,before,'MASTER_RETURN_DELETE')})}
export async function saveEvidence(u:SessionUser,id:string,slot:number,fileUrl:string){if(![1,2].includes(slot)||!fileUrl.trim())throw new Error('INVALID_EVIDENCE');return withTransaction(async c=>{const m=await lock(c,u,id);if(!canEditReception(u.role,m.status))throw new Error('LOCKED');const before=m.status==='DRAFT'?null:await snap(c,id);await c.query("INSERT INTO return_evidence(movement_id,file_url,uploaded_by,slot) VALUES($1,$2,$3,$4) ON CONFLICT(movement_id,slot) DO UPDATE SET file_url=EXCLUDED.file_url,uploaded_by=EXCLUDED.uploaded_by,uploaded_at=now()",[id,fileUrl.trim(),u.id,slot]);if(before)await correction(c,u,m,before,'MASTER_RETURN_EVIDENCE')})}
export async function deleteEvidence(u:SessionUser,id:string,slot:number){return withTransaction(async c=>{const m=await lock(c,u,id);if(!canEditReception(u.role,m.status))throw new Error('LOCKED');const before=m.status==='DRAFT'?null:await snap(c,id);await c.query("DELETE FROM return_evidence WHERE movement_id=$1 AND slot=$2",[id,slot]);if(before)await correction(c,u,m,before,'MASTER_RETURN_EVIDENCE_DELETE')})}
export async function closeReturn(u:SessionUser,id:string){return withTransaction(async c=>{const m=await lock(c,u,id);if(m.status!=='DRAFT')throw new Error('ALREADY_CLOSED');const q=await c.query<{n:number;damaged:number;evidence:number}>("SELECT (SELECT count(*)::int FROM return_lines WHERE movement_id=$1) n,(SELECT count(*)::int FROM return_lines WHERE movement_id=$1 AND condition='DAMAGED') damaged,(SELECT count(*)::int FROM return_evidence WHERE movement_id=$1) evidence",[id]);if(q.rows[0].n<1)throw new Error('RETURN_WITHOUT_LINES');if(q.rows[0].damaged>0&&q.rows[0].evidence<1)throw new Error('DAMAGE_EVIDENCE_REQUIRED');await c.query("UPDATE inventory_movements SET status='CLOSED',closed_by=$1,closed_at=now(),updated_at=now() WHERE id=$2",[u.id,id]);const s=await snap(c,id);await c.query("INSERT INTO movement_versions(movement_id,version,snapshot,created_by) VALUES($1,1,$2::jsonb,$3) ON CONFLICT DO NOTHING",[id,JSON.stringify(s.snapshot),u.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action,new_value) VALUES($1,$2,$3,'RETURN_CLOSED',$4::jsonb)",[u.id,m.branch_id,id,JSON.stringify(s.snapshot)])})}
export async function registerReturnPos(u:SessionUser,id:string){if(u.role==='OPERATIVE')throw new Error('SOLO_ENCARGADO');return withTransaction(async c=>{const m=await lock(c,u,id),corr=canRegisterPosCorrection(m.status,m.pos_registered_at);if(!corr&&!canRegisterPos(m.status,m.pos_registered_at))throw new Error('POS_NOT_ALLOWED');await c.query("UPDATE inventory_movements SET status=$1::movement_status,pos_registered_by=$2,pos_registered_at=now(),updated_at=now() WHERE id=$3",[corr?'POS_RECONCILED':'POS_REGISTERED',u.id,id]);await c.query("INSERT INTO pos_registration_events(movement_id,branch_id,event_type,movement_version,user_id) VALUES($1,$2,$3::pos_event_type,$4,$5)",[id,m.branch_id,corr?'CORRECTION':'INITIAL',m.current_version,u.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action) VALUES($1,$2,$3,$4)",[u.id,m.branch_id,id,corr?'RETURN_POS_CORRECTION_REGISTERED':'RETURN_POS_REGISTERED'])})}
