import "server-only";
import type { PoolClient } from "@neondatabase/serverless";
import { withTransaction } from "@/lib/db";
import { assertBranchAccess } from "@/lib/auth/authorization";
import type { SessionUser } from "@/lib/auth/types";
import { assertPositiveQuantity } from "./policy";
type TS="DRAFT"|"SENT"|"WAITING_RECEIPT"|"RECEIVED"|"RECEIVED_WITH_DIFFERENCES"|"PENDING_POS"|"COMPLETED"|"CANCELLED";type T={id:string;movement_id:string;origin_branch_id:string;destination_branch_id:string;status:TS;origin_pos_registered_at:string|null;destination_pos_registered_at:string|null};
async function lock(c:PoolClient,id:string){const q=await c.query<T>("SELECT id::text,movement_id::text,origin_branch_id::text,destination_branch_id::text,status::text,origin_pos_registered_at,destination_pos_registered_at FROM transfers WHERE movement_id=$1::uuid FOR UPDATE",[id]);if(!q.rows[0])throw new Error('NOT_FOUND');return q.rows[0]}
async function access(u:SessionUser,t:T,side:'origin'|'destination'){await assertBranchAccess(u,side==='origin'?t.origin_branch_id:t.destination_branch_id)}
async function snap(c:PoolClient,t:T){const q=await c.query<{snapshot:Record<string,unknown>;total:number}>(`SELECT jsonb_build_object('movement',to_jsonb(m),'transfer',to_jsonb(t),'lines',COALESCE((SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object('product_name',p.name) ORDER BY l.id) FROM transfer_lines l JOIN products p ON p.id=l.product_id WHERE l.transfer_id=t.id),'[]'::jsonb)) snapshot,COALESCE((SELECT sum(COALESCE(received_quantity,sent_quantity))::int FROM transfer_lines WHERE transfer_id=t.id),0)::int total FROM transfers t JOIN inventory_movements m ON m.id=t.movement_id WHERE t.id=$1`,[t.id]);return q.rows[0]}
async function version(c:PoolClient,u:SessionUser,t:T,before:Awaited<ReturnType<typeof snap>>,action:string){const q=await c.query<{current_version:number}>("UPDATE inventory_movements SET current_version=current_version+1,updated_at=now() WHERE id=$1 RETURNING current_version",[t.movement_id]);const v=q.rows[0].current_version,after=await snap(c,t);await c.query("INSERT INTO movement_versions(movement_id,version,snapshot,created_by) VALUES($1,$2,$3::jsonb,$4)",[t.movement_id,v,JSON.stringify(after.snapshot),u.id]);await c.query("INSERT INTO movement_change_sets(movement_id,from_version,to_version,previous_total,new_total,quantity_difference,changes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8)",[t.movement_id,v-1,v,before.total,after.total,after.total-before.total,JSON.stringify([{action}]),u.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action,previous_value,new_value) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb)",[u.id,t.origin_branch_id,t.movement_id,action,JSON.stringify(before.snapshot),JSON.stringify(after.snapshot)])}
export async function createTransfer(u:SessionUser,origin:string,destination:string){if(origin===destination)throw new Error('SAME_BRANCH');await assertBranchAccess(u,origin);return withTransaction(async c=>{const active=await c.query("SELECT count(*)::int n FROM branches WHERE id=ANY($1::uuid[]) AND status='ACTIVE'",[[origin,destination]]);if(active.rows[0].n!==2)throw new Error('INVALID_BRANCH');const folio=`TRA-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`,m=await c.query<{id:string}>("INSERT INTO inventory_movements(folio,movement_type,branch_id,created_by) VALUES($1,'TRANSFER',$2,$3) RETURNING id::text",[folio,origin,u.id]);await c.query("INSERT INTO transfers(movement_id,origin_branch_id,destination_branch_id) VALUES($1,$2,$3)",[m.rows[0].id,origin,destination]);return m.rows[0].id})}
export async function saveTransferLine(u:SessionUser,id:string,x:{lineId?:string;productId:string;quantity:number}){assertPositiveQuantity(x.quantity);return withTransaction(async c=>{const t=await lock(c,id);await access(u,t,'origin');if(t.status!=='DRAFT')throw new Error('LOCKED');const valid=await c.query("SELECT 1 FROM products WHERE id=$1 AND status='ACTIVE'",[x.productId]);if(!valid.rowCount)throw new Error('INVALID_PRODUCT');if(x.lineId)await c.query("UPDATE transfer_lines SET product_id=$1,sent_quantity=$2 WHERE id=$3 AND transfer_id=$4",[x.productId,x.quantity,x.lineId,t.id]);else await c.query("INSERT INTO transfer_lines(transfer_id,product_id,sent_quantity) VALUES($1,$2,$3)",[t.id,x.productId,x.quantity])})}
export async function deleteTransferLine(u:SessionUser,id:string,lineId:string){return withTransaction(async c=>{const t=await lock(c,id);await access(u,t,'origin');if(t.status!=='DRAFT')throw new Error('LOCKED');await c.query("DELETE FROM transfer_lines WHERE id=$1 AND transfer_id=$2",[lineId,t.id])})}
export async function sendTransfer(u:SessionUser,id:string){return withTransaction(async c=>{const t=await lock(c,id);await access(u,t,'origin');if(t.status!=='DRAFT')throw new Error('ALREADY_SENT');const n=await c.query<{n:number}>("SELECT count(*)::int n FROM transfer_lines WHERE transfer_id=$1",[t.id]);if(!n.rows[0].n)throw new Error('TRANSFER_WITHOUT_LINES');await c.query("UPDATE transfers SET status='WAITING_RECEIPT',sent_by=$1,sent_at=now() WHERE id=$2",[u.id,t.id]);await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action) VALUES($1,$2,$3,'TRANSFER_SENT')",[u.id,t.origin_branch_id,id])})}
export async function receiveTransfer(u:SessionUser,id:string,lines:{id:string;received:number;reason?:string}[]){return withTransaction(async c=>{const t=await lock(c,id);await access(u,t,'destination');if(t.status!=='WAITING_RECEIPT'&&t.status!=='RECEIVED_WITH_DIFFERENCES')throw new Error('NOT_RECEIVABLE');const before=await snap(c,t),db=await c.query<{id:string;sent_quantity:number}>("SELECT id::text,sent_quantity FROM transfer_lines WHERE transfer_id=$1 ORDER BY id FOR UPDATE",[t.id]);if(lines.length!==db.rows.length)throw new Error('ALL_LINES_REQUIRED');for(const row of db.rows){const x=lines.find(v=>v.id===row.id);if(!x||!Number.isInteger(x.received)||x.received<0)throw new Error('INVALID_RECEIVED_QUANTITY');const d=x.received-row.sent_quantity,reason=(x.reason||'').trim();if(d!==0&&!reason)throw new Error('DIFFERENCE_REASON_REQUIRED');await c.query("UPDATE transfer_lines SET received_quantity=$1,difference=$2,difference_reason=$3 WHERE id=$4",[x.received,d,d===0?null:reason,row.id])}const diff=lines.some((x,i)=>x.received!==db.rows.find(r=>r.id===x.id)?.sent_quantity);await c.query("UPDATE transfers SET status=$1::transfer_status,received_by=$2,received_at=now() WHERE id=$3",[diff?'RECEIVED_WITH_DIFFERENCES':'PENDING_POS',u.id,t.id]);await version(c,u,t,before,diff?'TRANSFER_RECEIVED_WITH_DIFFERENCES':'TRANSFER_RECEIVED')})}
export async function resolveDifferences(u:SessionUser,id:string){if(u.role!=='MASTER')throw new Error('MASTER_REQUIRED');return withTransaction(async c=>{const t=await lock(c,id);if(t.status!=='RECEIVED_WITH_DIFFERENCES')throw new Error('NO_DIFFERENCES');const before=await snap(c,t);await c.query("UPDATE transfer_lines SET sent_quantity=received_quantity,difference=0 WHERE transfer_id=$1 AND received_quantity IS NOT NULL",[t.id]);await c.query("UPDATE transfers SET status='PENDING_POS' WHERE id=$1",[t.id]);await version(c,u,t,before,'TRANSFER_DIFFERENCES_RESOLVED')})}
export async function registerTransferPos(u:SessionUser,id:string,side:'origin'|'destination'){return withTransaction(async c=>{const t=await lock(c,id);await access(u,t,side);if(t.status!=='PENDING_POS')throw new Error('POS_NOT_ALLOWED');const col=side==='origin'?'origin':'destination';if(side==='origin'&&t.origin_pos_registered_at||side==='destination'&&t.destination_pos_registered_at)throw new Error('POS_ALREADY_REGISTERED');await c.query(`UPDATE transfers SET ${col}_pos_registered_by=$1,${col}_pos_registered_at=now() WHERE id=$2`,[u.id,t.id]);await c.query("INSERT INTO pos_registration_events(movement_id,branch_id,event_type,movement_version,user_id) SELECT $1,$2,'INITIAL',current_version,$3 FROM inventory_movements WHERE id=$1",[id,side==='origin'?t.origin_branch_id:t.destination_branch_id,u.id]);const fresh=await c.query<{done:boolean}>("SELECT origin_pos_registered_at IS NOT NULL AND destination_pos_registered_at IS NOT NULL done FROM transfers WHERE id=$1",[t.id]);if(fresh.rows[0].done){await c.query("UPDATE transfers SET status='COMPLETED' WHERE id=$1",[t.id]);await c.query("UPDATE inventory_movements SET status='CLOSED',closed_by=$1,closed_at=now(),updated_at=now() WHERE id=$2",[u.id,id])}await c.query("INSERT INTO audit_events(user_id,branch_id,movement_id,action) VALUES($1,$2,$3,$4)",[u.id,side==='origin'?t.origin_branch_id:t.destination_branch_id,id,side==='origin'?'TRANSFER_ORIGIN_POS':'TRANSFER_DESTINATION_POS'])})}
