"use client";
import "./tiktok-labels.css";
import {useEffect,useMemo,useState} from "react";

type Item={id:string;product_id:string|null;product_name:string;variation:string;tiktok_sku_id:string|null;seller_sku:string|null;sku_source:string;updated_at:string};type OrderItem={id:string;product_name:string;variation:string;seller_sku:string|null;qty:number};type Order={id:string;name:string;items:OrderItem[];created_at:string;updated_at:string};
export default function TikTokLabels(){
 const [items,setItems]=useState<Item[]>([]),[q,setQ]=useState(""),[filter,setFilter]=useState("ALL"),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[mode,setMode]=useState<"CATALOG"|"GENERATE"|"ORDERS">("CATALOG"),[product,setProduct]=useState(""),[productQ,setProductQ]=useState(""),[step,setStep]=useState<"SELECT"|"ORDER">("SELECT"),[qty,setQty]=useState<Record<string,number>>({}),[orders,setOrders]=useState<Order[]>([]),[orderName,setOrderName]=useState(""),[editingOrder,setEditingOrder]=useState<string|null>(null);
 async function load(){const r=await fetch("/api/tiktok-labels");if(r.ok)setItems(await r.json())}
 async function loadOrders(){const r=await fetch("/api/tiktok-labels/orders");if(r.ok)setOrders(await r.json())} useEffect(()=>{load();loadOrders()},[]);
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setBusy(true);setMsg("");try{const fd=new FormData();fd.append("file",f);const r=await fetch("/api/tiktok-labels/import",{method:"POST",body:fd});let j:any={};try{j=await r.json()}catch{}setMsg(r.ok?`Importación lista: ${j.imported} variantes · ${j.missingSku} sin SKU`:j.error||`No se pudo importar el archivo (${r.status})`);if(r.ok)await load()}catch{setMsg("No se pudo importar el archivo. Intenta nuevamente.")}finally{setBusy(false);e.target.value=""}}
 async function save(id:string,sku:string){const r=await fetch("/api/tiktok-labels",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,sku})});const j=await r.json();if(!r.ok){setMsg(j.error||"No se pudo guardar");return}load()}
 const products=useMemo(()=>Array.from(new Map(items.map(x=>[x.product_name,{name:x.product_name,productId:x.product_id}])).values()).sort((a,b)=>a.name.localeCompare(b.name)),[items]);
 const productResults=useMemo(()=>{const s=productQ.trim().toLowerCase();if(!s)return products;return products.filter(p=>p.name.toLowerCase().includes(s)||(p.productId||"").toLowerCase().includes(s))},[products,productQ]);
 const shown=useMemo(()=>items.filter(x=>{const isMissing=!x.seller_sku;if(mode==="GENERATE"&&isMissing)return false;if(mode==="GENERATE"&&product&&x.product_name!==product)return false;if(filter==="WITH"&&isMissing)return false;if(filter==="MISSING"&&!isMissing)return false;return (x.product_name+" "+x.variation+" "+(x.seller_sku||"")).toLowerCase().includes(q.toLowerCase())}),[items,q,filter,mode,product]);
 const missing=items.filter(x=>!x.seller_sku).length, selected=items.filter(x=>(qty[x.id]||0)>0),total=selected.reduce((a,x)=>a+(qty[x.id]||0),0);
 const assignedFor=(p:string)=>items.filter(x=>x.product_name===p).reduce((a,x)=>a+(qty[x.id]||0),0);
 const selectedProducts=Array.from(new Set(selected.map(x=>x.product_name)));
 function printLabels(){if(!total)return;window.print()}
 function addQty(id:string,n:number){setQty(v=>({...v,[id]:Math.max(0,n)}))}
 function resetOrder(){setQty({});setProduct("");setProductQ("");setQ("");setStep("SELECT");setOrderName("");setEditingOrder(null)}
 async function saveOrder(){if(!total)return;const name=(orderName||prompt("Nombre del pedido:")||"").trim();if(!name)return;const payload=selected.map(x=>({id:x.id,product_name:x.product_name,variation:x.variation,seller_sku:x.seller_sku,qty:qty[x.id]||0}));const r=await fetch("/api/tiktok-labels/orders",{method:editingOrder?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:editingOrder,name,items:payload})});if(r.ok){await loadOrders();resetOrder();setMode("ORDERS");setMsg("Pedido guardado correctamente")}}
 function editOrder(o:Order){const next:Record<string,number>={};o.items.forEach(x=>next[x.id]=x.qty);setQty(next);setOrderName(o.name);setEditingOrder(o.id);setMode("GENERATE");setStep("SELECT");setProduct("");setProductQ("");setQ("")}
 async function deleteOrder(id:string){if(!confirm("¿Eliminar este pedido?"))return;await fetch("/api/tiktok-labels/orders",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});loadOrders()}
 function zplOrder(o:Order){const esc=(s:string)=>String(s||"").replace(/[\\^~]/g," ");let z="";o.items.forEach(x=>{for(let i=0;i<x.qty;i++)z+=`^XA^PW320^LL200^CI28^FO12,18^A0N,22,20^FB296,2,0,C^FD${esc(x.product_name)}^FS^FO12,72^A0N,20,18^FB296,2,0,C^FD${esc(x.variation)}^FS^FO45,125^BY2^BCN,45,N,N,N^FD${esc(x.seller_sku||"")}^FS^FO12,174^A0N,18,18^FB296,1,0,C^FD${esc(x.seller_sku||"")}^FS^XZ\n`});const blob=new Blob([z],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(o.name||"pedido").replace(/[^a-z0-9_-]+/gi,"_")+".txt";a.click();URL.revokeObjectURL(a.href)}
 return <div className="ttPage">
  <div className="ttHero"><div><span className="ttEyebrow">CELULARTE · TIKTOK SHOP</span><h1>Etiquetas TikTok</h1><p>Catálogo independiente para administrar SKU y generar etiquetas.</p></div>{mode==="CATALOG"&&<label className="ttUpload">{busy?"Importando…":"Importar Excel de TikTok"}<input type="file" accept=".xlsx,.xls" onChange={upload} disabled={busy}/></label>}</div>
  <div className="ttTabs"><button className={mode==="CATALOG"?"active":""} onClick={()=>setMode("CATALOG")}>Catálogo TikTok</button><button className={mode==="GENERATE"?"active":""} onClick={()=>{setMode("GENERATE");setFilter("ALL");setQ("")}}>Generar etiquetas</button><button className={mode==="ORDERS"?"active":""} onClick={()=>{setMode("ORDERS");loadOrders()}}>Pedidos</button></div>
  {msg&&<div className="ttNotice">{msg}</div>}
  {mode==="CATALOG"?<><div className="ttStats"><div><b>{items.length}</b><span>Variantes</span></div><div><b>{items.length-missing}</b><span>Con SKU</span></div><div><b>{missing}</b><span>Falta SKU</span></div></div>
  <div className="ttToolbar"><input placeholder="Buscar producto, variación o SKU…" value={q} onChange={e=>setQ(e.target.value)}/><div className="ttFilters">{[["ALL","Todos"],["WITH","Con SKU"],["MISSING","Sin SKU"]].map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>
  <div className="ttList">{shown.map(x=><div className="ttRow" key={x.id}><div className="ttInfo"><b>{x.product_name}</b><span>{x.variation||"Sin variación"}</span></div><Sku item={x} save={save}/></div>)}{!shown.length&&<div className="ttEmpty">No hay variantes para mostrar.</div>}</div></>:
  <>{step==="SELECT"?<>
  <div className="ttGenerateTop"><div><b>{selected.length}</b><span>variantes seleccionadas</span></div><div><b>{total}</b><span>etiquetas</span></div><button disabled={!total} onClick={()=>setStep("ORDER")}>Ver mi pedido</button></div>
  <div className="ttToolbar"><input placeholder="Buscar por nombre o ID de producto…" value={productQ} onChange={e=>{setProductQ(e.target.value);setProduct("")}}/>{!product&&<div className="ttProductDropdown">{productResults.length?productResults.map(p=><button type="button" className="ttProductOption" key={p.name} onClick={()=>{setProduct(p.name);setProductQ(p.name);setQ("")}}><b>{p.name}</b><span>{p.productId?`ID producto: ${p.productId}`:"Seleccionar producto"}</span></button>):<div className="ttProductEmpty">No encontramos productos con ese nombre o ID.</div>}</div>}{product&&<input placeholder="Buscar modelo, color o SKU…" value={q} onChange={e=>setQ(e.target.value)}/>}</div>
  {product?<><div className="ttStats"><div><b>{shown.length}</b><span>Variantes</span></div><div><b>{assignedFor(product)}</b><span>Etiquetas seleccionadas</span></div></div><div className="ttList">{shown.map(x=><div className={"ttRow ttGenerateRow "+((qty[x.id]||0)>0?"selected":"")} key={x.id}><div className="ttInfo"><b>{x.variation||"Sin variación"}</b><em>SKU: {x.seller_sku}</em></div><div className="ttQty"><button onClick={()=>addQty(x.id,(qty[x.id]||0)-1)}>−</button><input type="number" min="0" value={qty[x.id]||0} onFocus={e=>{if((qty[x.id]||0)===0)e.currentTarget.select()}} onClick={e=>{if((qty[x.id]||0)===0)e.currentTarget.select()}} onChange={e=>addQty(x.id,Number(e.target.value)||0)}/><button onClick={()=>addQty(x.id,(qty[x.id]||0)+1)}>+</button></div></div>)}{!shown.length&&<div className="ttEmpty">No hay variantes con SKU para este producto.</div>}</div></>:<div className="ttEmpty">Busca un producto por nombre o por ID. Al seleccionarlo se desplegarán inmediatamente todos sus modelos y colores.</div>}
  </>:mode==="GENERATE"?<>
  <div className="ttGenerateTop"><div><b>{selected.length}</b><span>variantes en tu pedido</span></div><div><b>{total}</b><span>etiquetas totales</span></div><button onClick={saveOrder}>{editingOrder?"Guardar cambios":"Generar pedido"}</button></div>
  <div className="ttToolbar"><button onClick={()=>setStep("SELECT")}>← Seguir agregando productos</button><button onClick={resetOrder}>Nuevo pedido</button></div>
  <div className="ttList">{selectedProducts.map(p=><div key={p}><div className="ttNotice"><b>{p}</b> · {assignedFor(p)} etiquetas</div>{selected.filter(x=>x.product_name===p).map(x=><div className="ttRow ttGenerateRow selected" key={x.id}><div className="ttInfo"><b>{x.variation||"Sin variación"}</b><em>SKU: {x.seller_sku}</em></div><div className="ttQty"><button onClick={()=>addQty(x.id,(qty[x.id]||0)-1)}>−</button><input type="number" min="0" value={qty[x.id]||0} onFocus={e=>{if((qty[x.id]||0)===0)e.currentTarget.select()}} onClick={e=>{if((qty[x.id]||0)===0)e.currentTarget.select()}} onChange={e=>addQty(x.id,Number(e.target.value)||0)}/><button onClick={()=>addQty(x.id,(qty[x.id]||0)+1)}>+</button></div></div>)}</div>)}</div>
  </>:null}
  {mode==="ORDERS"&&<div className="ttOrders"><div className="ttOrdersHead"><div><h2>Pedidos</h2><p>Pedidos guardados de etiquetas TikTok.</p></div><button onClick={()=>{resetOrder();setMode("GENERATE")}}>+ Generar pedido</button></div>{orders.length?orders.map(o=>{const totalO=o.items.reduce((a,x)=>a+x.qty,0);return <div className="ttOrderCard" key={o.id}><div><input className="ttOrderName" value={o.name} onChange={e=>setOrders(v=>v.map(x=>x.id===o.id?{...x,name:e.target.value}:x))} onBlur={async()=>{await fetch("/api/tiktok-labels/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:o.id,name:o.name,items:o.items})});loadOrders()}}/><span>{o.items.length} variantes · {totalO} etiquetas</span></div><div className="ttOrderActions"><button onClick={()=>editOrder(o)}>Editar / agregar artículos</button><button onClick={()=>zplOrder(o)}>Generar etiqueta TXT ZPL</button><button className="danger" onClick={()=>deleteOrder(o.id)}>Eliminar</button></div></div>}):<div className="ttEmpty">Todavía no hay pedidos guardados.</div>}</div>}
  <div className="ttPrintArea">{selected.flatMap(x=>Array.from({length:qty[x.id]||0},(_,i)=><div className="ttLabel" key={x.id+"-"+i}><strong>{x.product_name}</strong><span>{x.variation}</span><b>{x.seller_sku}</b><small>TIKTOK SHOP</small></div>))}</div></>}
 </div>
}
function Sku({item,save}:{item:Item;save:(id:string,sku:string)=>void}){const [v,setV]=useState(item.seller_sku||"");useEffect(()=>setV(item.seller_sku||""),[item.seller_sku]);return <div className="ttSku"><small>{item.seller_sku?"SKU vendedor":"FALTA SKU"}</small><div><input value={v} placeholder="Asignar SKU" onChange={e=>setV(e.target.value.toUpperCase())}/>{v.trim()!==(item.seller_sku||"")&&<button onClick={()=>save(item.id,v.trim())}>Guardar</button>}</div></div>}
